### ISSUE TITLE
Bootstrapping fails when it tries to upgrade setuptools

### ISSUE THREAD

**Issue by do3cc** [buildout/buildout#237]
This might be a setuptools bug after all, I am not sure.
Steps to reproduce
```
$ virtualenv test
$ cd test && . ./bin/activate
$ pip install -U setuptools==8.3
$ wget https://bootstrap.pypa.io/bootstrap-buildout.py
$ python bootstrap-buildout.py
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-12.1.zip
Extracting in /tmp/tmpydOe3Q
Now working in /tmp/tmpydOe3Q/setuptools-12.1
Building a Setuptools egg in /tmp/tmppVetCW
/tmp/tmppVetCW/setuptools-12.1-py2.7.egg
Traceback (most recent call last):
  File "bootstrap-buildout.py", line 98, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 174, in use_setuptools
  File "<string>", line 129, in _do_download
  File "build/bdist.linux-x86_64/egg/setuptools/__init__.py", line 11, in <module>
  File "build/bdist.linux-x86_64/egg/setuptools/extension.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 19, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 83, in <module>
AttributeError: 'module' object has no attribute '_vendor'
```

I went into this with a debugger but there is some weird stuff going on for which my python fu is inadequate it seems.

I set setuptools to 8.3 because the error only appears with 8.3. It will not appear if there is no need to upgrade setuptools.

**Comment by Themanwithoutaplan** [comment]
FWIW this *seems* to be restricted to Python 2.6

**Comment by do3cc** [comment]
I am having this Issue with python 2.7

**Comment by gforcada** [comment]
@do3cc have you tried pinning setuptools to 8.3 even though you install it with pip it's still downloading 12.1, try:

```
python bootstrap-buildout.py --setuptools-version=8.3
```

**Comment by gforcada** [comment]
This seems to work, just tried it locally.

**Comment by do3cc** [comment]
Yes, this works, but is no solution. I want to be able to use the newest version. doing pip install -U setuptools is just a crutch for this.

**Comment by davisagli** [comment]
FWIW I usually run buildout in a `virtualenv --no-setuptools` so that bootstrap can install whatever version of setuptools it wants without upgrading.

**Comment by do3cc** [comment]
Yes, this is another workaround

**Comment by Trii** [comment]
I am having the same issue as shown here in my travis-ci build

https://travis-ci.org/Trii/appengine-buildout-template/builds/50526312

```
$ source ~/virtualenv/python2.7/bin/activate
$ python --version
Python 2.7.9
$ pip --version
pip 6.0.7 from /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages (python 2.7)
$ if [ ! -f './bin/buildout' ]; then python bootstrap-buildout.py; fi;
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-12.1.zip
Extracting in /tmp/tmppTXsmU
Now working in /tmp/tmppTXsmU/setuptools-12.1
Building a Setuptools egg in /tmp/tmpaKt0UF
/tmp/tmpaKt0UF/setuptools-12.1-py2.7.egg
Traceback (most recent call last):
  File "bootstrap-buildout.py", line 98, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 174, in use_setuptools
  File "<string>", line 129, in _do_download
  File "build/bdist.linux-x86_64/egg/setuptools/__init__.py", line 11, in <module>
  File "build/bdist.linux-x86_64/egg/setuptools/extension.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 19, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 83, in <module>
AttributeError: 'module' object has no attribute '_vendor'
The command "if [ ! -f './bin/buildout' ]; then python bootstrap-buildout.py; fi;" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by romanofski** [comment]
This seems to be fixed with setuptools 12.2 and is not a zc.buildout regression. Here is the ticket: https://bitbucket.org/pypa/setuptools/issue/345/installation-issues-on-travis-ci

**Comment by do3cc** [comment]
I can confirm that this works with setuptools 12.2. Time to unpin my jenkins again.
